import { FaStar } from "react-icons/fa";

export const ProductData = [
  {
    id: 1,
    productImage: "../products/Yellow-Shoes.jpeg",
    productName: "DNK Yellow Shoes",
    prevPrice: 150,
    newPrice: 120,
    productCategory: "Men",
    star: <FaStar />,
    quantity: 0,
  },
  {
    id: 2,
    productImage: "../products/Blue-Shoes.jpeg",
    productName: "DNK white Shoes",
    prevPrice: 280,
    newPrice: 240,
    productCategory: "Men",
    star: <FaStar />,
    quantity: 0,
  },
  {
    id: 3,
    productImage: "../products/Brown-Jeans.jpeg",
    productName: "Dark Brown Jeans",
    prevPrice: 200,
    newPrice: 150,
    productCategory: "Men",
    star: <FaStar />,
    quantity: 0,
  },
  {
    id: 4,
    productImage: "../products/Blue-Denim-Jeans.jpeg",
    productName: "Blue Denim Jeans",
    prevPrice: 180,
    newPrice: 150,
    productCategory: "Women",
    star: <FaStar />,
    quantity: 0,
  },
  {
    id: 5,
    productImage: "../products/Basic-Gray-Jeans.jpeg",
    productName: "Basic Gray Jeans",
    prevPrice: 180,
    newPrice: 150,
    productCategory: "Women",
    star: <FaStar />,
    quantity: 0,
  },
  {
    id: 6,
    productImage: "../products/Blue-Denim-Shorts.jpeg",
    productName: "Blue Denim Shorts",
    prevPrice: 150,
    newPrice: 130,
    productCategory: "Women",
    star: <FaStar />,
    quantity: 0,
  },
  {
    id: 7,
    productImage: "../products/Boho-Bangle-Bracelet.jpeg",
    productName: "Boho Bangle Bracelet",
    prevPrice: 200,
    newPrice: 170,
    productCategory: "Accessories",
    star: <FaStar />,
    quantity: 0,
  },
  {
    id: 8,
    productImage: "../products/Anchor-Bracelet.jpeg",
    productName: "Anchor Bracelet",
    prevPrice: 200,
    newPrice: 180,
    productCategory: "Accessories",
    star: <FaStar />,
    quantity: 0,
  },
  {
    id: 9,
    productImage: "../products/Light-Brown-Purse.jpeg",
    productName: "Light Brown Purse",
    prevPrice: 180,
    newPrice: 150,
    productCategory: "Accessories",
    star: <FaStar />,
    quantity: 0,
  },
  {
    id: 10,
    productImage: "../products/Bright-Red-Bag.jpeg",
    productName: "Bright Red Bag",
    prevPrice: 160,
    newPrice: 140,
    productCategory: "Accessories",
    star: <FaStar />,
    quantity: 0,
  },
];
